package geodata

import "github.com/vincentchyu/photo-processing/internal/geocoding"

// curatedEuropePoints 欧洲精选摄影地与主要城市
var curatedEuropePoints = []geocoding.GeoPoint{
	{Lat: 51.5074, Lon: -0.1278, Country: "英国", CountryCode: "GB", Province: "英格兰", City: "伦敦", District: "大本钟/伦敦眼/塔桥", Source: "pack_europe"},
	{Lat: 55.9533, Lon: -3.1883, Country: "英国", CountryCode: "GB", Province: "苏格兰", City: "爱丁堡", District: "爱丁堡城堡/皇家一英里", Source: "pack_europe"},
	{Lat: 57.4778, Lon: -4.2247, Country: "英国", CountryCode: "GB", Province: "苏格兰", City: "高地", District: "天空岛/尼斯湖/苏格兰高地", Source: "pack_europe"},
	{Lat: 48.8566, Lon: 2.3522, Country: "法国", CountryCode: "FR", Province: "法兰西岛", City: "巴黎", District: "埃菲尔铁塔/卢浮宫/凯旋门/塞纳河", Source: "pack_europe"},
	{Lat: 43.7102, Lon: 7.2620, Country: "法国", CountryCode: "FR", Province: "普罗旺斯-阿尔卑斯-蓝色海岸", City: "尼斯", District: "天使湾/戛纳/普罗旺斯薰衣草田", Source: "pack_europe"},
	{Lat: 48.6360, Lon: -1.5115, Country: "法国", CountryCode: "FR", Province: "诺曼底大区", City: "芒什省", District: "圣米歇尔山", Source: "pack_europe"},
	{Lat: 45.9237, Lon: 6.8694, Country: "法国", CountryCode: "FR", Province: "奥弗涅-罗讷-阿尔卑斯", City: "霞慕尼", District: "勃朗峰/南针峰", Source: "pack_europe"},
	{Lat: 52.5200, Lon: 13.4050, Country: "德国", CountryCode: "DE", Province: "柏林州", City: "柏林", District: "勃兰登堡门/博物馆岛", Source: "pack_europe"},
	{Lat: 48.1351, Lon: 11.5820, Country: "德国", CountryCode: "DE", Province: "巴伐利亚州", City: "慕尼黑", District: "玛利亚广场/国王湖/魔法森林", Source: "pack_europe"},
	{Lat: 47.5576, Lon: 10.7498, Country: "德国", CountryCode: "DE", Province: "巴伐利亚州", City: "菲森", District: "新天鹅堡", Source: "pack_europe"},
	{Lat: 41.9028, Lon: 12.4964, Country: "意大利", CountryCode: "IT", Province: "拉齐奥大区", City: "罗马", District: "古罗马斗兽场/特雷维喷泉/梵蒂冈", Source: "pack_europe"},
	{Lat: 43.7696, Lon: 11.2558, Country: "意大利", CountryCode: "IT", Province: "托斯卡纳大区", City: "佛罗伦萨", District: "圣母百花大教堂/乌菲兹美术馆/托斯卡纳丝柏之路", Source: "pack_europe"},
	{Lat: 45.4408, Lon: 12.3155, Country: "意大利", CountryCode: "IT", Province: "威尼托大区", City: "威尼斯", District: "圣马可广场/大运河/彩色岛", Source: "pack_europe"},
	{Lat: 44.1461, Lon: 9.6439, Country: "意大利", CountryCode: "IT", Province: "利古里亚大区", City: "拉斯佩齐亚", District: "五渔村国家公园(韦尔纳扎/马纳罗拉)", Source: "pack_europe"},
	{Lat: 46.5383, Lon: 12.1372, Country: "意大利", CountryCode: "IT", Province: "威尼托/特伦蒂诺", City: "科尔蒂纳丹佩佐", District: "多洛米蒂山脉/三峰山/富纳斯山谷/刀锋山", Source: "pack_europe"},
	{Lat: 46.5935, Lon: 7.9090, Country: "瑞士", CountryCode: "CH", Province: "伯尔尼州", City: "因特拉肯", District: "少女峰/格林德瓦/梦幻山坡/图恩湖", Source: "pack_europe"},
	{Lat: 45.9763, Lon: 7.7491, Country: "瑞士", CountryCode: "CH", Province: "瓦莱州", City: "采尔马特", District: "马特洪峰/戈尔内格拉特", Source: "pack_europe"},
	{Lat: 47.0502, Lon: 8.3093, Country: "瑞士", CountryCode: "CH", Province: "琉森州", City: "琉森", District: "卡佩尔廊桥/皮拉图斯山/瑞吉山", Source: "pack_europe"},
	{Lat: 41.3879, Lon: 2.1699, Country: "西班牙", CountryCode: "ES", Province: "加泰罗尼亚", City: "巴塞罗那", District: "圣家族大教堂/巴特罗之家/奎尔公园", Source: "pack_europe"},
	{Lat: 40.4168, Lon: -3.7038, Country: "西班牙", CountryCode: "ES", Province: "马德里自治区", City: "马德里", District: "马德里王宫/普拉多博物馆", Source: "pack_europe"},
	{Lat: 37.3891, Lon: -5.9845, Country: "西班牙", CountryCode: "ES", Province: "安达卢西亚", City: "塞维利亚", District: "西班牙广场/阿尔罕布拉宫(格拉纳达)/龙达", Source: "pack_europe"},
	{Lat: 38.7223, Lon: -9.1393, Country: "葡萄牙", CountryCode: "PT", Province: "里斯本大区", City: "里斯本", District: "贝伦塔/热罗尼莫斯修道院/罗卡角", Source: "pack_europe"},
	{Lat: 41.1579, Lon: -8.6291, Country: "葡萄牙", CountryCode: "PT", Province: "北部大区", City: "波尔图", District: "路易一世大桥/莱罗书店/杜罗河", Source: "pack_europe"},
	{Lat: 64.1466, Lon: -21.9426, Country: "冰岛", CountryCode: "IS", Province: "大雷克雅未克区", City: "雷克雅未克", District: "哈尔格林姆教堂/蓝湖温泉/黄金圈", Source: "pack_europe"},
	{Lat: 63.5320, Lon: -19.0060, Country: "冰岛", CountryCode: "IS", Province: "南部区", City: "维克", District: "黑沙滩/塞里雅兰瀑布/斯科加瀑布", Source: "pack_europe"},
	{Lat: 64.0489, Lon: -16.1794, Country: "冰岛", CountryCode: "IS", Province: "南部区", City: "霍芬", District: "杰古沙龙冰河湖/钻石冰沙滩/瓦特纳冰川", Source: "pack_europe"},
	{Lat: 68.1667, Lon: 13.7500, Country: "挪威", CountryCode: "NO", Province: "诺尔兰郡", City: "罗弗敦群岛", District: "雷讷/白雪渔村/极光峡湾", Source: "pack_europe"},
	{Lat: 60.3913, Lon: 5.3221, Country: "挪威", CountryCode: "NO", Province: "韦斯特兰郡", City: "卑尔根", District: "布吕根/松恩峡湾/哈当厄尔峡湾/恶魔之舌", Source: "pack_europe"},
	{Lat: 59.3293, Lon: 18.0686, Country: "瑞典", CountryCode: "SE", Province: "斯德哥尔摩省", City: "斯德哥尔摩", District: "斯德哥尔摩老城/瓦萨沉船博物馆", Source: "pack_europe"},
	{Lat: 60.1699, Lon: 24.9384, Country: "芬兰", CountryCode: "FI", Province: "新地区", City: "赫尔辛基", District: "赫尔辛基大教堂/白教堂", Source: "pack_europe"},
	{Lat: 66.5039, Lon: 25.7294, Country: "芬兰", CountryCode: "FI", Province: "拉普兰区", City: "罗瓦涅米", District: "圣诞老人村/极地驯鹿雪橇", Source: "pack_europe"},
	{Lat: 52.3676, Lon: 4.9041, Country: "荷兰", CountryCode: "NL", Province: "北荷兰省", City: "阿姆斯特丹", District: "阿姆斯特丹运河/羊角村/库肯霍夫郁金香公园/风车村", Source: "pack_europe"},
	{Lat: 50.8503, Lon: 4.3517, Country: "比利时", CountryCode: "BE", Province: "布鲁塞尔首都大区", City: "布鲁塞尔", District: "大广场/原子球塔/布鲁日古城", Source: "pack_europe"},
	{Lat: 48.2082, Lon: 16.3738, Country: "奥地利", CountryCode: "AT", Province: "维也纳州", City: "维也纳", District: "美泉宫/霍夫堡皇宫/金色大厅", Source: "pack_europe"},
	{Lat: 47.5622, Lon: 13.6493, Country: "奥地利", CountryCode: "AT", Province: "上奥地利州", City: "哈尔施塔特", District: "哈尔施塔特湖/明信片角度", Source: "pack_europe"},
	{Lat: 50.0755, Lon: 14.4378, Country: "捷克", CountryCode: "CZ", Province: "布拉格市", City: "布拉格", District: "查理大桥/布拉格城堡/克鲁姆洛夫(CK小镇)", Source: "pack_europe"},
	{Lat: 47.4979, Lon: 19.0402, Country: "匈牙利", CountryCode: "HU", Province: "布达佩斯市", City: "布达佩斯", District: "渔人堡/国会大厦/链子桥/多瑙河", Source: "pack_europe"},
	{Lat: 37.9838, Lon: 23.7275, Country: "希腊", CountryCode: "GR", Province: "阿提卡大区", City: "雅典", District: "雅典卫城/帕特农神庙", Source: "pack_europe"},
	{Lat: 36.3932, Lon: 25.4615, Country: "希腊", CountryCode: "GR", Province: "南爱琴大区", City: "圣托里尼", District: "伊亚蓝顶教堂/爱琴海落日/费拉小镇", Source: "pack_europe"},
}

// curatedNorthAmericaPoints 北美洲精选摄影地与主要城市
var curatedNorthAmericaPoints = []geocoding.GeoPoint{
	{Lat: 40.7128, Lon: -74.0060, Country: "美国", CountryCode: "US", Province: "纽约州", City: "纽约市", District: "曼哈顿/时代广场/中央公园/自由女神像", Source: "pack_north-america"},
	{Lat: 37.7749, Lon: -122.4194, Country: "美国", CountryCode: "US", Province: "加利福尼亚州", City: "旧金山", District: "金门大桥/九曲花街/渔人码头/硅谷", Source: "pack_north-america"},
	{Lat: 34.0522, Lon: -118.2437, Country: "美国", CountryCode: "US", Province: "加利福尼亚州", City: "洛杉矶", District: "好莱坞/格里菲斯天文台/圣莫尼卡海滩", Source: "pack_north-america"},
	{Lat: 37.8651, Lon: -119.5383, Country: "美国", CountryCode: "US", Province: "加利福尼亚州", City: "马里波萨县", District: "优胜美地国家公园(酋长岩/半圆顶)", Source: "pack_north-america"},
	{Lat: 36.2704, Lon: -121.8081, Country: "美国", CountryCode: "US", Province: "加利福尼亚州", City: "蒙特雷县", District: "加州一号公路/大苏尔/比克斯比大桥", Source: "pack_north-america"},
	{Lat: 36.1699, Lon: -115.1398, Country: "美国", CountryCode: "US", Province: "内华达州", City: "拉斯维加斯", District: "拉斯维加斯大道/百乐宫喷泉", Source: "pack_north-america"},
	{Lat: 36.0544, Lon: -112.1401, Country: "美国", CountryCode: "US", Province: "亚利桑那州", City: "可可尼诺县", District: "科罗拉多大峡谷国家公园(南缘/北缘)", Source: "pack_north-america"},
	{Lat: 36.8619, Lon: -111.5106, Country: "美国", CountryCode: "US", Province: "亚利桑那州", City: "佩吉市", District: "羚羊峡谷/马蹄湾/鲍威尔湖", Source: "pack_north-america"},
	{Lat: 38.7331, Lon: -109.5925, Country: "美国", CountryCode: "US", Province: "犹他州", City: "莫阿布", District: "拱门国家公园(精致拱门)/峡谷地国家公园", Source: "pack_north-america"},
	{Lat: 37.5930, Lon: -112.1871, Country: "美国", CountryCode: "US", Province: "犹他州", City: "加菲尔德县", District: "布莱斯峡谷国家公园/锡安国家公园", Source: "pack_north-america"},
	{Lat: 44.4280, Lon: -110.5885, Country: "美国", CountryCode: "US", Province: "怀俄明州", City: "帕克县", District: "黄石国家公园(大棱镜/老忠实/黄石湖)", Source: "pack_north-america"},
	{Lat: 43.7904, Lon: -110.6818, Country: "美国", CountryCode: "US", Province: "怀俄明州", City: "提顿县", District: "大提顿国家公园/珍妮湖/杰克逊霍尔", Source: "pack_north-america"},
	{Lat: 47.6062, Lon: -122.3321, Country: "美国", CountryCode: "US", Province: "华盛顿州", City: "西雅图", District: "太空针塔/派克市场/雷尼尔雪山国家公园", Source: "pack_north-america"},
	{Lat: 21.3069, Lon: -157.8583, Country: "美国", CountryCode: "US", Province: "夏威夷州", City: "檀香山", District: "欧胡岛/威基基海滩/恐龙湾/珍珠港", Source: "pack_north-america"},
	{Lat: 20.7984, Lon: -156.3319, Country: "美国", CountryCode: "US", Province: "夏威夷州", City: "茂宜岛", District: "哈雷阿卡拉国家公园(日出云海)/哈纳之路", Source: "pack_north-america"},
	{Lat: 61.2181, Lon: -149.9003, Country: "美国", CountryCode: "US", Province: "阿拉斯加州", City: "安克雷奇", District: "德纳里国家公园(麦金利山)/基奈峡湾", Source: "pack_north-america"},
	{Lat: 49.2827, Lon: -123.1207, Country: "加拿大", CountryCode: "CA", Province: "不列颠哥伦比亚省", City: "温哥华", District: "斯坦利公园/卡皮拉诺吊桥/惠斯勒", Source: "pack_north-america"},
	{Lat: 51.1784, Lon: -115.5708, Country: "加拿大", CountryCode: "CA", Province: "阿尔伯塔省", City: "班夫", District: "班夫国家公园/路易斯湖/梦莲湖/弓湖", Source: "pack_north-america"},
	{Lat: 52.8734, Lon: -118.0814, Country: "加拿大", CountryCode: "CA", Province: "阿尔伯塔省", City: "贾斯珀", District: "贾斯珀国家公园/哥伦比亚冰原/阿萨巴斯卡瀑布", Source: "pack_north-america"},
	{Lat: 43.6532, Lon: -79.3832, Country: "加拿大", CountryCode: "CA", Province: "安大略省", City: "多伦多", District: "CN塔/尼亚加拉大瀑布", Source: "pack_north-america"},
	{Lat: 46.8139, Lon: -71.2080, Country: "加拿大", CountryCode: "CA", Province: "魁北克省", City: "魁北克市", District: "芳缇娜城堡饭店/小香普兰街/圣劳伦斯河", Source: "pack_north-america"},
	{Lat: 62.4540, Lon: -114.3718, Country: "加拿大", CountryCode: "CA", Province: "西北地区", City: "黄刀镇", District: "耶洛奈夫极光观测村/大奴湖", Source: "pack_north-america"},
	{Lat: 19.4326, Lon: -99.1332, Country: "墨西哥", CountryCode: "MX", Province: "墨西哥城", City: "墨西哥城", District: "宪法广场/特奥蒂瓦坎太阳月亮金字塔", Source: "pack_north-america"},
	{Lat: 21.1619, Lon: -86.8515, Country: "墨西哥", CountryCode: "MX", Province: "金塔纳罗奥州", City: "坎昆", District: "奇琴伊察玛雅遗址/粉红湖/图卢姆", Source: "pack_north-america"},
}

// curatedOceaniaPoints 大洋洲与澳新精选摄影地
var curatedOceaniaPoints = []geocoding.GeoPoint{
	{Lat: -33.8688, Lon: 151.2093, Country: "澳大利亚", CountryCode: "AU", Province: "新南威尔士州", City: "悉尼", District: "悉尼歌剧院/海港大桥/邦迪海滩/蓝山国家公园", Source: "pack_oceania"},
	{Lat: -37.8136, Lon: 144.9631, Country: "澳大利亚", CountryCode: "AU", Province: "维多利亚州", City: "墨尔本", District: "涂鸦街/普芬比利蒸汽火车/菲利普岛小企鹅", Source: "pack_oceania"},
	{Lat: -38.6658, Lon: 143.1047, Country: "澳大利亚", CountryCode: "AU", Province: "维多利亚州", City: "大洋路", District: "十二使徒岩/洛克阿德大峡谷/阿波罗湾", Source: "pack_oceania"},
	{Lat: -16.9186, Lon: 145.7781, Country: "澳大利亚", CountryCode: "AU", Province: "昆士兰州", City: "凯恩斯", District: "大堡礁(心形礁/绿岛)/库兰达热带雨林", Source: "pack_oceania"},
	{Lat: -28.0167, Lon: 153.4000, Country: "澳大利亚", CountryCode: "AU", Province: "昆士兰州", City: "黄金海岸", District: "冲浪者天堂/春溪国家公园(蓝光萤火虫)", Source: "pack_oceania"},
	{Lat: -25.3444, Lon: 131.0369, Country: "澳大利亚", CountryCode: "AU", Province: "北领地", City: "乌鲁鲁", District: "艾尔斯岩(红土中心)/卡塔丘塔/帝王谷", Source: "pack_oceania"},
	{Lat: -42.8821, Lon: 147.3272, Country: "澳大利亚", CountryCode: "AU", Province: "塔斯马尼亚州", City: "霍巴特", District: "威灵顿山/摇篮山/酒杯湾/薰衣草农场", Source: "pack_oceania"},
	{Lat: -31.9505, Lon: 115.8605, Country: "澳大利亚", CountryCode: "AU", Province: "西澳大利亚州", City: "珀斯", District: "罗特尼斯岛(短尾矮袋鼠)/尖峰石阵/粉红湖", Source: "pack_oceania"},
	{Lat: -45.0312, Lon: 168.6626, Country: "新西兰", CountryCode: "NZ", Province: "奥塔哥大区", City: "皇后镇", District: "瓦卡蒂普湖/天空缆车/箭镇秋景/格林诺奇(魔戒小镇)", Source: "pack_oceania"},
	{Lat: -44.6943, Lon: 169.1321, Country: "新西兰", CountryCode: "NZ", Province: "奥塔哥大区", City: "瓦纳卡", District: "瓦纳卡孤树/罗伊峰(Roys Peak)", Source: "pack_oceania"},
	{Lat: -44.6714, Lon: 167.9256, Country: "新西兰", CountryCode: "NZ", Province: "南地大区", City: "米尔福德峡湾", District: "米尔福德峡湾/峡湾国家公园", Source: "pack_oceania"},
	{Lat: -43.7342, Lon: 170.0962, Country: "新西兰", CountryCode: "NZ", Province: "坎特伯雷大区", City: "库克山", District: "奥拉基库克山国家公园/胡克谷步道/塔斯曼冰川", Source: "pack_oceania"},
	{Lat: -44.0044, Lon: 170.4772, Country: "新西兰", CountryCode: "NZ", Province: "坎特伯雷大区", City: "特卡波", District: "特卡波湖/好牧羊人教堂/国际暗夜星空保护区", Source: "pack_oceania"},
	{Lat: -36.8485, Lon: 174.7633, Country: "新西兰", CountryCode: "NZ", Province: "奥克兰大区", City: "奥克兰", District: "天空塔/怀赫科岛/霍比特人村(马塔马塔)", Source: "pack_oceania"},
	{Lat: -38.1368, Lon: 176.2497, Country: "新西兰", CountryCode: "NZ", Province: "丰盛湾大区", City: "罗托鲁瓦", District: "地热喷泉/毛利文化村/红木森林", Source: "pack_oceania"},
	{Lat: -17.7134, Lon: 178.0650, Country: "斐济", CountryCode: "FJ", Province: "西部大区", City: "楠迪", District: "玛玛努卡群岛/亚萨瓦群岛", Source: "pack_oceania"},
	{Lat: -17.6509, Lon: -149.4260, Country: "法属波利尼西亚", CountryCode: "PF", Province: "背风群岛", City: "大溪地/波拉波拉岛", District: "奥特马努峰/水上屋泻湖", Source: "pack_oceania"},
}

// curatedSouthAmericaPoints 南美洲精选摄影地
var curatedSouthAmericaPoints = []geocoding.GeoPoint{
	{Lat: -13.1631, Lon: -72.5450, Country: "秘鲁", CountryCode: "PE", Province: "库斯科大区", City: "马丘比丘", District: "印加古城遗迹/华纳比丘", Source: "pack_south-america"},
	{Lat: -13.5319, Lon: -71.9675, Country: "秘鲁", CountryCode: "PE", Province: "库斯科大区", City: "库斯科", District: "萨克塞瓦曼/彩虹山(Vinicunca)/圣谷", Source: "pack_south-america"},
	{Lat: -20.2667, Lon: -67.5833, Country: "玻利维亚", CountryCode: "BO", Province: "波托西省", City: "乌尤尼", District: "乌尤尼盐沼(天空之镜)/红湖火烈鸟", Source: "pack_south-america"},
	{Lat: -16.5000, Lon: -68.1500, Country: "玻利维亚", CountryCode: "BO", Province: "拉巴斯省", City: "拉巴斯", District: "缆车观景台/的的喀喀湖/月亮谷", Source: "pack_south-america"},
	{Lat: -50.4967, Lon: -73.1378, Country: "阿根廷", CountryCode: "AR", Province: "圣克鲁斯省", City: "埃尔卡拉法特", District: "佩里托莫雷诺冰川/冰川国家公园", Source: "pack_south-america"},
	{Lat: -49.3315, Lon: -72.8864, Country: "阿根廷", CountryCode: "AR", Province: "圣克鲁斯省", City: "埃尔恰尔滕", District: "菲茨罗伊峰(Fitz Roy)/塞罗托雷峰", Source: "pack_south-america"},
	{Lat: -54.8019, Lon: -68.3030, Country: "阿根廷", CountryCode: "AR", Province: "火地省", City: "乌斯怀亚", District: "世界尽头/比格尔海峡/火地岛国家公园", Source: "pack_south-america"},
	{Lat: -34.6037, Lon: -58.3816, Country: "阿根廷", CountryCode: "AR", Province: "布宜诺斯艾利斯", City: "布宜诺斯艾利斯", District: "博卡区/五月广场/雅典人书店", Source: "pack_south-america"},
	{Lat: -25.6953, Lon: -54.4367, Country: "阿根廷/巴西", CountryCode: "AR", Province: "米西奥内斯省", City: "伊瓜苏", District: "伊瓜苏大瀑布(魔鬼之喉)", Source: "pack_south-america"},
	{Lat: -51.2532, Lon: -72.8814, Country: "智利", CountryCode: "CL", Province: "麦哲伦大区", City: "百内国家公园", District: "百内三塔/百内角/格雷冰川", Source: "pack_south-america"},
	{Lat: -22.9110, Lon: -68.1994, Country: "智利", CountryCode: "CL", Province: "安托法加斯塔大区", City: "圣佩德罗德阿塔卡马", District: "阿塔卡马沙漠/月亮谷/间歇泉/高原盐湖", Source: "pack_south-america"},
	{Lat: -27.1127, Lon: -109.3497, Country: "智利", CountryCode: "CL", Province: "瓦尔帕莱索大区", City: "复活节岛", District: "拉诺拉拉库采石场/摩艾石像群", Source: "pack_south-america"},
	{Lat: -22.9068, Lon: -43.1729, Country: "巴西", CountryCode: "BR", Province: "里约热内卢州", City: "里约热内卢", District: "耶稣山救世基督像/糖面包山/科帕卡巴纳海滩", Source: "pack_south-america"},
	{Lat: -3.1190, Lon: -60.0217, Country: "巴西", CountryCode: "BR", Province: "亚马孙州", City: "玛瑙斯", District: "亚马孙热带雨林/黑河与索利蒙伊斯河黑白交汇", Source: "pack_south-america"},
}

// curatedAfricaPoints 非洲精选摄影地
var curatedAfricaPoints = []geocoding.GeoPoint{
	{Lat: 29.9792, Lon: 31.1342, Country: "埃及", CountryCode: "EG", Province: "吉萨省", City: "吉萨", District: "吉萨金字塔群/狮身人面像", Source: "pack_africa"},
	{Lat: 25.6872, Lon: 32.6396, Country: "埃及", CountryCode: "EG", Province: "卢克索省", City: "卢克索", District: "帝王谷/卡纳克神庙/热气球俯瞰尼罗河", Source: "pack_africa"},
	{Lat: 22.3372, Lon: 31.6258, Country: "埃及", CountryCode: "EG", Province: "阿斯旺省", City: "阿布辛贝", District: "阿布辛贝神庙/菲莱神庙", Source: "pack_africa"},
	{Lat: -1.5000, Lon: 35.2500, Country: "肯尼亚", CountryCode: "KE", Province: "裂谷省", City: "纳罗克郡", District: "马赛马拉国家保护区(动物大迁徙/角马过河)", Source: "pack_africa"},
	{Lat: -0.3667, Lon: 36.0833, Country: "肯尼亚", CountryCode: "KE", Province: "裂谷省", City: "纳库鲁郡", District: "纳库鲁湖国家公园/火烈鸟湖/东非大裂谷", Source: "pack_africa"},
	{Lat: -2.6000, Lon: 37.2500, Country: "肯尼亚", CountryCode: "KE", Province: "裂谷省", City: "卡贾多郡", District: "安博塞利国家公园(乞力马扎罗雪山象群背景)", Source: "pack_africa"},
	{Lat: -2.3333, Lon: 34.8333, Country: "坦桑尼亚", CountryCode: "TZ", Province: "马拉区", City: "塞伦盖蒂", District: "塞伦盖蒂国家公园/恩戈罗恩戈罗火山口", Source: "pack_africa"},
	{Lat: -3.0674, Lon: 37.3556, Country: "坦桑尼亚", CountryCode: "TZ", Province: "乞力马扎罗区", City: "莫希", District: "乞力马扎罗山顶(非洲之巅乌呼鲁峰)", Source: "pack_africa"},
	{Lat: -6.1659, Lon: 39.2026, Country: "坦桑尼亚", CountryCode: "TZ", Province: "桑给巴尔", City: "桑给巴尔市", District: "石头城/白沙滩/香料岛", Source: "pack_africa"},
	{Lat: -33.9249, Lon: 18.4241, Country: "南非", CountryCode: "ZA", Province: "西开普省", City: "开普敦", District: "桌山/好望角/博尔德斯海滩企鹅保护区/维多利亚阿尔弗雷德码头", Source: "pack_africa"},
	{Lat: -24.0000, Lon: 31.5000, Country: "南非", CountryCode: "ZA", Province: "普马兰加省/林波波省", City: "克鲁格", District: "克鲁格国家公园(非洲五大兽Safari)", Source: "pack_africa"},
	{Lat: -24.7500, Lon: 15.2833, Country: "纳米比亚", CountryCode: "NA", Province: "哈达普区", City: "索苏斯盐沼", District: "纳米布红沙漠/45号沙丘/死亡谷枯树/十字角海豹滩", Source: "pack_africa"},
	{Lat: -17.9243, Lon: 25.8572, Country: "津巴布韦/赞比亚", CountryCode: "ZW", Province: "北马塔贝莱兰省", City: "维多利亚瀑布城", District: "维多利亚大瀑布/魔鬼泳池/赞比西河日落巡游", Source: "pack_africa"},
	{Lat: 31.6295, Lon: -7.9811, Country: "摩洛哥", CountryCode: "MA", Province: "马拉喀什-萨菲大区", City: "马拉喀什", District: "德吉玛不夜广场/马约尔花园/巴希亚王宫", Source: "pack_africa"},
	{Lat: 35.1688, Lon: -5.2684, Country: "摩洛哥", CountryCode: "MA", Province: "丹吉尔-得土安-胡塞马大区", City: "舍夫沙万", District: "蓝色小镇舍夫沙万麦地那老城", Source: "pack_africa"},
	{Lat: 31.1333, Lon: -3.9833, Country: "摩洛哥", CountryCode: "MA", Province: "德拉-塔菲拉勒特大区", City: "梅尔祖卡", District: "撒哈拉沙漠(厄尔切比沙丘)/星空营地", Source: "pack_africa"},
}
